version: 2.1
commands:
  install-bazel:
    steps:
      - run:
          name: Install bazel
          command: |
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.24.0/bazel-0.24.0-installer-linux-x86_64.sh
            chmod +x bazel-0.24.0-installer-linux-x86_64.sh
            sudo ./bazel-0.24.0-installer-linux-x86_64.sh
            rm ./bazel-0.24.0-installer-linux-x86_64.sh
            bazel info release
  restore-caches:
    steps:
      - restore_cache:
          keys:
            - "android_sdk"
      - restore_cache:
          keys:
            - "v4-bazel_cache"
  save-caches:
    steps:
      - save_cache:
          key: "android_sdk"
          paths:
            - "/home/circleci/android_sdk"

      - save_cache:
          key: "v4-bazel_cache"
          paths:
            - "/home/circleci/.cache/bazel/"
jobs:
  lint:
    working_directory: ~/ng/
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-bazel
      - run: './tools/checkstyle/check-for-missing-targets.sh'
      - run: './fix-formatting.sh'

  build:
    working_directory: ~/ng/
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-bazel
      - restore-caches
      - run: './tools/get_android_sdk.sh'
      - run:
          name: "Hasadna: building"
          command: ./compile.sh build
          environment:
            ANDROID_HOME: /home/circleci/android_sdk/
      - run:
          name: "Hasadna: testing"
          command: ./compile.sh test
          environment:
            ANDROID_HOME: /home/circleci/android_sdk/
      - save-caches

workflows:
  default_workflow:
    jobs:
      - lint
      - build:
          requires:
            - lint
